# Generated by Django 5.0.2 on 2024-02-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_course_video_course_usercourse_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
